service: www-cyclonusbooks-com
image: red-panda-industries/www.cyclonusbooks.com

servers:
  - 1337.attac.us

proxy:
  ssl: true
  hosts:
    - www.cyclonusbooks.com
    - cyclonusbooks.com

ssh:
  user: george

builder:
  arch: amd64

registry:
  server: ghcr.io
  username: jackwillis
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] %>
